### ISSUE TITLE
pipes in $XDG_RUNTIME_DIR/wyebrun/clients not cleaned up

### ISSUE THREAD

**Issue by herrsimon** [jun7/wyebadblock#3]
Hello,

I just noticed that wyebadblock does not delete the pipes in $XDG_RUNTIME_DIR/wyebrun/clients when it stops running. In my case (don't restart my computer very often and open a new browser instance for almost every webpage), this means that just within a few days hundreds of pipes are piled up in the directory. Could you please change this behaviour?

**Comment by jun7** [comment]
Somehow  `__attribute__((destructor)) removepp` is not called.

**Comment by jun7** [comment]
Somehow it is fixed.
