### ISSUE TITLE
whitelist for domains

### ISSUE THREAD

**Issue by nihilowy** [jun7/wyebadblock#8]
I wonder is it possible, in ephy-uri-tester or in ab.c ?

**Comment by jun7** [comment]
I think easylist.txt has whitelist. See easylist's document.
Or wyebadblock has API mode to mix  browsers' block system. See https://github.com/jun7/wyebadblock#full-control

**Comment by nihilowy** [comment]
sorry I mean blacklist. I am studying  Your code but cant understand:

 "In api mode wyebab doesn't block URIs but keeps alive server proc and set the check function to the page object. So you can call the check func where ever as below.

bool (*checkf)(const char *, const char *) =
	g_object_get_data(G_OBJECT(webkitwebpage), "wyebcheck");
if (checkf)
	passed = checkf(requesturi, pageuri); 

"

If I want to stop  blocking i.e for google.com what I have to add to my code ?
what function to use ? sorry for stupid questions.

**Comment by jun7** [comment]
I think editing easylist.txt is most simplified approach for the purpose.
The easylist.txt is a filter list, so it should have white/black list functionality.
Did you read the filter's specification?

wyebadblock only uses 'easylist.txt' file but it means only a file name. you can edit it, even can use other filters you want.

**Comment by nihilowy** [comment]
ok I think I was misleaded by  this code in ephy-uri-tester: 


> 
>   /* FIXME: No support for domain= */
>   if (strstr (line, "domain="))
>     return;
> 

now seems it is something alse, but anyway thank You for explanations.

**Comment by jun7** [comment]
Anyway thank you for reporting!
